M48
; DRILL file KiCad 10.0.5 date 2026-08-26T03:11:26
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-08-26T03:11:26+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.850
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.200
%
G90
G05
T1
X103.5Y-56.5
X103.5Y-63.5
T2
X59.03Y-81.265
X59.03Y-86.115
T3
X56.0Y-80.965
X56.0Y-86.415
M30
